/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/namespace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a list of namespaces
         * @description Retrieve a list of namespaces for the authenticated organization.
         */
        get: operations["listNamespaces"];
        put?: never;
        /**
         * Create a namespace.
         * @description Create a namespace for the authenticated organization.
         */
        post: operations["createNamespace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/namespace/{namespaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a namespace
         * @description Retrieve the info for a namespace.
         */
        get: operations["getNamespace"];
        put?: never;
        post?: never;
        /**
         * Delete a namespace.
         * @description Delete a namespace for the authenticated organization. This will delete all the data associated with the namespace.
         */
        delete: operations["deleteNamespace"];
        options?: never;
        head?: never;
        /**
         * Update a namespace.
         * @description Update a namespace for the authenticated organization. If there is no change, return it as it is.
         */
        patch: operations["updateNamespace"];
        trace?: never;
    };
    "/v1/namespace/{namespaceId}/ingest-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a list of ingest jobs
         * @description Retrieve a paginated list of ingest jobs for the authenticated organization.
         */
        get: operations["listIngestJobs"];
        put?: never;
        /**
         * Create an ingest job
         * @description Create an ingest job for the authenticated organization.
         */
        post: operations["createIngestJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/namespace/{namespaceId}/ingest-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve an ingest job
         * @description Retrieve the info for an ingest job.
         */
        get: operations["getIngestJobInfo"];
        put?: never;
        post?: never;
        /**
         * Delete an ingest job
         * @description Delete an ingest job for the authenticated organization.
         */
        delete: operations["deleteIngestJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/namespace/{namespaceId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a list of documents
         * @description Retrieve a paginated list of documents for the authenticated organization.
         */
        get: operations["listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/namespace/{namespaceId}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a document
         * @description Retrieve the info for a document.
         */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        /**
         * Delete a document
         * @description Delete a document for the authenticated organization.
         */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/namespace/{namespaceId}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search a namespace
         * @description Search a namespace for a query.
         */
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The embedding model config. If not provided, our managed embedding model will be used. Note: You can't change the embedding model config after the namespace is created. */
        EmbeddingConfigSchema: {
            /** @enum {string} */
            provider: "OPENAI";
            /** @enum {string} */
            model: "text-embedding-3-small" | "text-embedding-3-large";
            apiKey: string;
        } | {
            /** @enum {string} */
            provider: "AZURE_OPENAI";
            /** @enum {string} */
            model: "text-embedding-3-small" | "text-embedding-3-large";
            /**
             * Format: uri
             * @description The base URL of the Azure OpenAI API.
             * @example https://example.openai.azure.com/openai/deployments
             */
            baseUrl: string;
            /** @description The deployment name of the Azure OpenAI API. */
            deployment: string;
            /** @description The API key for the Azure OpenAI API. */
            apiKey: string;
            /** @description The API version for the Azure OpenAI API. */
            apiVersion?: string;
        } | {
            /** @enum {string} */
            provider: "VOYAGE";
            /** @enum {string} */
            model: "voyage-3-large" | "voyage-3" | "voyage-3-lite" | "voyage-code-3" | "voyage-finance-2" | "voyage-law-2";
            apiKey: string;
        } | {
            /** @enum {string} */
            provider: "GOOGLE";
            /** @enum {string} */
            model: "text-embedding-004";
            apiKey: string;
        };
        /** @description The vector store config. If not provided, our managed vector store will be used. Note: You can't change the vector store config after the namespace is created. */
        VectorStoreSchema: {
            /** @enum {string} */
            provider: "PINECONE";
            /** @description The API key for the Pinecone index. */
            apiKey: string;
            /**
             * Format: uri
             * @description The host of the Pinecone index.
             * @example https://example.svc.aped-1234-a56b.pinecone.io
             */
            indexHost: string;
        };
        /** Namespace */
        NamespaceSchema: {
            /** @description The unique ID of the namespace. */
            id: string;
            /** @description The name of the namespace. */
            name: string;
            /** @description The slug of the namespace. */
            slug: string;
            /** @description The ID of the organization that owns the namespace. */
            organizationId: string;
            /** @description The date and time the namespace was created. */
            createdAt: string;
            /** @default null */
            embeddingConfig: components["schemas"]["EmbeddingConfigSchema"] | null;
            /** @default null */
            vectorStoreConfig: components["schemas"]["VectorStoreSchema"] | null;
        };
        /** Ingest Job */
        IngestJobSchema: {
            /** @description The unique ID of the ingest job. */
            id: string;
            /** @description The namespace ID of the ingest job. */
            namespaceId: string;
            /**
             * @description The tenant ID of the ingest job.
             * @default null
             */
            tenantId: string | null;
            status: components["schemas"]["IngestJobStatusSchema"];
            /**
             * @description The error message of the ingest job. Only exists when the status is failed.
             * @default null
             */
            error: string | null;
            /** @description The ingest job payload. */
            payload: {
                /** @enum {string} */
                type: "TEXT";
                /** @description The text to ingest. */
                text: string;
                /** @description The name of the ingest job. */
                name?: string | null;
            } | {
                /** @enum {string} */
                type: "FILE";
                /** @description The URL of the file to ingest. */
                fileUrl: string;
                /** @description The name of the ingest job. */
                name?: string | null;
            } | {
                /** @enum {string} */
                type: "MANAGED_FILE";
                /** @description The key of the managed file to ingest. */
                key: string;
                /** @description The name of the ingest job. */
                name?: string | null;
            } | {
                /** @enum {string} */
                type: "URLS";
                /** @description The URLs to ingest. */
                urls: string[];
            };
            /**
             * @description The ingest job config.
             * @default null
             */
            config: {
                /** @description Custom chunk size. */
                chunkSize?: number;
                /** @description Custom chunk overlap. */
                chunkOverlap?: number;
                /** @description Custom metadata to be added to the ingested documents. */
                metadata?: {
                    [key: string]: unknown;
                };
                /**
                 * @description The chunking strategy to use. Defaults to `basic`.
                 * @enum {string}
                 */
                chunkingStrategy?: "basic" | "by_title";
                /**
                 * @description The strategy to use. Defaults to `auto`.
                 * @enum {string}
                 */
                strategy?: "auto" | "fast" | "hi_res" | "ocr_only";
            } | null;
            /** @description The date and time the namespace was created. */
            createdAt: string;
            /**
             * @description The date and time the ingest job was queued.
             * @default null
             */
            queuedAt: string | null;
            /**
             * @description The date and time the ingest job was pre-processed.
             * @default null
             */
            preProcessingAt: string | null;
            /**
             * @description The date and time the ingest job was processed.
             * @default null
             */
            processingAt: string | null;
            /**
             * @description The date and time the ingest job was completed.
             * @default null
             */
            completedAt: string | null;
            /**
             * @description The date and time the ingest job failed.
             * @default null
             */
            failedAt: string | null;
        };
        /**
         * @description The status of the ingest job.
         * @enum {string}
         */
        IngestJobStatusSchema: "BACKLOG" | "QUEUED" | "QUEUED_FOR_RESYNC" | "QUEUED_FOR_DELETE" | "PRE_PROCESSING" | "PROCESSING" | "DELETING" | "CANCELLING" | "COMPLETED" | "FAILED" | "CANCELLED";
        /** Document */
        DocumentSchema: {
            /** @description The unique ID of the document. */
            id: string;
            /** @description The ingest job ID of the document. */
            ingestJobId: string;
            /**
             * @description A unique external ID.
             * @default null
             */
            externalId: string | null;
            /**
             * @description The name of the document.
             * @default null
             */
            name: string | null;
            /**
             * @description The tenant ID of the ingest job.
             * @default null
             */
            tenantId: string | null;
            status: components["schemas"]["DocumentStatusSchema"];
            /**
             * @description The error message of the document. Only exists when the status is failed.
             * @default null
             */
            error: string | null;
            /** @description The source of the document. */
            source: {
                /** @enum {string} */
                type: "TEXT";
                /** @description The text to ingest. */
                text: string;
            } | {
                /** @enum {string} */
                type: "FILE";
                /** @description The URL of the file to ingest. */
                fileUrl: string;
            } | {
                /** @enum {string} */
                type: "MANAGED_FILE";
                /** @description The key of the managed file to ingest. */
                key: string;
            };
            /**
             * @description The properties of the document.
             * @default null
             */
            properties: {
                /** @description The size of the file in bytes. */
                fileSize: number;
                /**
                 * @description The MIME type of the file.
                 * @default null
                 */
                mimeType: string | null;
            } | null;
            /** @description The total number of chunks. */
            totalChunks: number;
            /** @description The total number of tokens. */
            totalTokens: number;
            /** @description The total number of characters. */
            totalCharacters: number;
            /** @description The total number of pages. Will be 0 if the document is not paged (e.g. PDF). */
            totalPages: number;
            /** @description The date and time the document was created. */
            createdAt: string;
            /**
             * @description The date and time the document was queued.
             * @default null
             */
            queuedAt: string | null;
            /**
             * @description The date and time the document was pre-processed.
             * @default null
             */
            preProcessingAt: string | null;
            /**
             * @description The date and time the document was processed.
             * @default null
             */
            processingAt: string | null;
            /**
             * @description The date and time the document was completed.
             * @default null
             */
            completedAt: string | null;
            /**
             * @description The date and time the document failed.
             * @default null
             */
            failedAt: string | null;
        };
        /**
         * @description The status of the document.
         * @enum {string}
         */
        DocumentStatusSchema: "BACKLOG" | "QUEUED" | "QUEUED_FOR_RESYNC" | "QUEUED_FOR_DELETE" | "PRE_PROCESSING" | "PROCESSING" | "DELETING" | "CANCELLING" | "COMPLETED" | "FAILED" | "CANCELLED";
    };
    responses: {
        /** @description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success: boolean;
                    error: {
                        /**
                         * @description A short code indicating the error code returned.
                         * @example bad_request
                         * @enum {string}
                         */
                        code: "bad_request";
                        /**
                         * @description A human readable explanation of what went wrong.
                         * @example The requested resource was not found.
                         */
                        message: string;
                        /**
                         * @description A link to our documentation with more details about this error code
                         * @example https://docs.agentset.com/api-reference/errors#bad-request
                         */
                        doc_url?: string;
                    };
                };
            };
        };
        /** @description Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response. */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success: boolean;
                    error: {
                        /**
                         * @description A short code indicating the error code returned.
                         * @example unauthorized
                         * @enum {string}
                         */
                        code: "unauthorized";
                        /**
                         * @description A human readable explanation of what went wrong.
                         * @example The requested resource was not found.
                         */
                        message: string;
                        /**
                         * @description A link to our documentation with more details about this error code
                         * @example https://docs.agentset.com/api-reference/errors#unauthorized
                         */
                        doc_url?: string;
                    };
                };
            };
        };
        /** @description The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server. */
        403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success: boolean;
                    error: {
                        /**
                         * @description A short code indicating the error code returned.
                         * @example forbidden
                         * @enum {string}
                         */
                        code: "forbidden";
                        /**
                         * @description A human readable explanation of what went wrong.
                         * @example The requested resource was not found.
                         */
                        message: string;
                        /**
                         * @description A link to our documentation with more details about this error code
                         * @example https://docs.agentset.com/api-reference/errors#forbidden
                         */
                        doc_url?: string;
                    };
                };
            };
        };
        /** @description The server cannot find the requested resource. */
        404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success: boolean;
                    error: {
                        /**
                         * @description A short code indicating the error code returned.
                         * @example not_found
                         * @enum {string}
                         */
                        code: "not_found";
                        /**
                         * @description A human readable explanation of what went wrong.
                         * @example The requested resource was not found.
                         */
                        message: string;
                        /**
                         * @description A link to our documentation with more details about this error code
                         * @example https://docs.agentset.com/api-reference/errors#not-found
                         */
                        doc_url?: string;
                    };
                };
            };
        };
        /** @description This response is sent when a request conflicts with the current state of the server. */
        409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success: boolean;
                    error: {
                        /**
                         * @description A short code indicating the error code returned.
                         * @example conflict
                         * @enum {string}
                         */
                        code: "conflict";
                        /**
                         * @description A human readable explanation of what went wrong.
                         * @example The requested resource was not found.
                         */
                        message: string;
                        /**
                         * @description A link to our documentation with more details about this error code
                         * @example https://docs.agentset.com/api-reference/errors#conflict
                         */
                        doc_url?: string;
                    };
                };
            };
        };
        /** @description This response is sent when the requested content has been permanently deleted from server, with no forwarding address. */
        410: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success: boolean;
                    error: {
                        /**
                         * @description A short code indicating the error code returned.
                         * @example invite_expired
                         * @enum {string}
                         */
                        code: "invite_expired";
                        /**
                         * @description A human readable explanation of what went wrong.
                         * @example The requested resource was not found.
                         */
                        message: string;
                        /**
                         * @description A link to our documentation with more details about this error code
                         * @example https://docs.agentset.com/api-reference/errors#invite-expired
                         */
                        doc_url?: string;
                    };
                };
            };
        };
        /** @description The request was well-formed but was unable to be followed due to semantic errors. */
        422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success: boolean;
                    error: {
                        /**
                         * @description A short code indicating the error code returned.
                         * @example unprocessable_entity
                         * @enum {string}
                         */
                        code: "unprocessable_entity";
                        /**
                         * @description A human readable explanation of what went wrong.
                         * @example The requested resource was not found.
                         */
                        message: string;
                        /**
                         * @description A link to our documentation with more details about this error code
                         * @example https://docs.agentset.com/api-reference/errors#unprocessable-entity
                         */
                        doc_url?: string;
                    };
                };
            };
        };
        /** @description The user has sent too many requests in a given amount of time ("rate limiting") */
        429: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success: boolean;
                    error: {
                        /**
                         * @description A short code indicating the error code returned.
                         * @example rate_limit_exceeded
                         * @enum {string}
                         */
                        code: "rate_limit_exceeded";
                        /**
                         * @description A human readable explanation of what went wrong.
                         * @example The requested resource was not found.
                         */
                        message: string;
                        /**
                         * @description A link to our documentation with more details about this error code
                         * @example https://docs.agentset.com/api-reference/errors#rate-limit_exceeded
                         */
                        doc_url?: string;
                    };
                };
            };
        };
        /** @description The server has encountered a situation it does not know how to handle. */
        500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success: boolean;
                    error: {
                        /**
                         * @description A short code indicating the error code returned.
                         * @example internal_server_error
                         * @enum {string}
                         */
                        code: "internal_server_error";
                        /**
                         * @description A human readable explanation of what went wrong.
                         * @example The requested resource was not found.
                         */
                        message: string;
                        /**
                         * @description A link to our documentation with more details about this error code
                         * @example https://docs.agentset.com/api-reference/errors#internal-server_error
                         */
                        doc_url?: string;
                    };
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listNamespaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The retrieved namespaces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["NamespaceSchema"][];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
    createNamespace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    slug: string;
                    embeddingConfig?: components["schemas"]["EmbeddingConfigSchema"];
                    vectorStoreConfig?: components["schemas"]["VectorStoreSchema"];
                };
            };
        };
        responses: {
            /** @description The created namespace */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["NamespaceSchema"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
    getNamespace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id of the namespace to retrieve. */
                namespaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The retrieved namespace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["NamespaceSchema"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
    deleteNamespace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id of the namespace to delete. */
                namespaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deleted namespace */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["NamespaceSchema"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
    updateNamespace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id of the namespace to update. */
                namespaceId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    slug?: string;
                };
            };
        };
        responses: {
            /** @description The updated namespace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["NamespaceSchema"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
    listIngestJobs: {
        parameters: {
            query?: {
                /** @description Statuses to filter by. */
                statuses?: components["schemas"]["IngestJobStatusSchema"][];
                /** @description The field to order by. Default is `createdAt`. */
                orderBy?: "createdAt";
                /** @description The sort order. Default is `desc`. */
                order?: "asc" | "desc";
                /** @description The cursor to paginate by. */
                cursor?: string;
                /** @description The direction to paginate by. */
                cursorDirection?: "forward" | "backward";
                /** @description The number of records to return per page. */
                perPage?: number;
            };
            header?: {
                /** @description The tenant id to use for the request. If not provided, the default tenant will be used. */
                "x-tenant-id"?: string;
            };
            path: {
                /** @description The id of the namespace to create the ingest job for. */
                namespaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The retrieved ingest jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["IngestJobSchema"][];
                        pagination: {
                            nextCursor: string | null;
                        };
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
    createIngestJob: {
        parameters: {
            query?: never;
            header?: {
                /** @description The tenant id to use for the request. If not provided, the default tenant will be used. */
                "x-tenant-id"?: string;
            };
            path: {
                /** @description The id of the namespace to create the ingest job for. */
                namespaceId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The ingest job payload. */
                    payload: {
                        /** @enum {string} */
                        type: "TEXT";
                        /** @description The text to ingest. */
                        text: string;
                        /** @description The name of the ingest job. */
                        name?: string | null;
                    } | {
                        /** @enum {string} */
                        type: "FILE";
                        /** @description The URL of the file to ingest. */
                        fileUrl: string;
                        /** @description The name of the ingest job. */
                        name?: string | null;
                    } | {
                        /** @enum {string} */
                        type: "MANAGED_FILE";
                        /** @description The key of the managed file to ingest. */
                        key: string;
                        /** @description The name of the ingest job. */
                        name?: string | null;
                    } | {
                        /** @enum {string} */
                        type: "URLS";
                        /** @description The URLs to ingest. */
                        urls: string[];
                    };
                    /** @description The ingest job config. */
                    config?: {
                        /** @description Custom chunk size. */
                        chunkSize?: number;
                        /** @description Custom chunk overlap. */
                        chunkOverlap?: number;
                        /** @description Custom metadata to be added to the ingested documents. */
                        metadata?: {
                            [key: string]: unknown;
                        };
                        /**
                         * @description The chunking strategy to use. Defaults to `basic`.
                         * @enum {string}
                         */
                        chunkingStrategy?: "basic" | "by_title";
                        /**
                         * @description The strategy to use. Defaults to `auto`.
                         * @enum {string}
                         */
                        strategy?: "auto" | "fast" | "hi_res" | "ocr_only";
                    };
                };
            };
        };
        responses: {
            /** @description The created ingest job */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["IngestJobSchema"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
    getIngestJobInfo: {
        parameters: {
            query?: never;
            header?: {
                /** @description The tenant id to use for the request. If not provided, the default tenant will be used. */
                "x-tenant-id"?: string;
            };
            path: {
                /** @description The id of the namespace to retrieve. */
                namespaceId: string;
                /** @description The id of the ingest job to retrieve. */
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The retrieved ingest job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["IngestJobSchema"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
    deleteIngestJob: {
        parameters: {
            query?: never;
            header?: {
                /** @description The tenant id to use for the request. If not provided, the default tenant will be used. */
                "x-tenant-id"?: string;
            };
            path: {
                /** @description The id of the namespace to delete. */
                namespaceId: string;
                /** @description The id of the ingest job to delete. */
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deleted ingest job */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["IngestJobSchema"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                /** @description Statuses to filter by. */
                statuses?: components["schemas"]["DocumentStatusSchema"][];
                /** @description The field to order by. Default is `createdAt`. */
                orderBy?: "createdAt";
                /** @description The order to sort by. Default is `desc`. */
                order?: "asc" | "desc";
                /** @description The ingest job ID to filter documents by. */
                ingestJobId?: string;
                /** @description The cursor to paginate by. */
                cursor?: string;
                /** @description The direction to paginate by. */
                cursorDirection?: "forward" | "backward";
                /** @description The number of records to return per page. */
                perPage?: number;
            };
            header?: {
                /** @description The tenant id to use for the request. If not provided, the default tenant will be used. */
                "x-tenant-id"?: string;
            };
            path: {
                /** @description The id of the namespace to create the ingest job for. */
                namespaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The retrieved ingest jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DocumentSchema"][];
                        pagination: {
                            nextCursor: string | null;
                        };
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: {
                /** @description The tenant id to use for the request. If not provided, the default tenant will be used. */
                "x-tenant-id"?: string;
            };
            path: {
                /** @description The id of the namespace to retrieve. */
                namespaceId: string;
                /** @description The id of the document to retrieve. */
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The retrieved ingest job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DocumentSchema"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: {
                /** @description The tenant id to use for the request. If not provided, the default tenant will be used. */
                "x-tenant-id"?: string;
            };
            path: {
                /** @description The id of the namespace to delete. */
                namespaceId: string;
                /** @description The id of the document to delete. */
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deleted document */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DocumentSchema"];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: {
                /** @description The tenant id to use for the request. If not provided, the default tenant will be used. */
                "x-tenant-id"?: string;
            };
            path: {
                /** @description The id of the namespace to search. */
                namespaceId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The query to search for. */
                    query: string;
                    /**
                     * @description The number of results to fetch from the vector store. Defaults to `10`.
                     * @default 10
                     */
                    topK?: number;
                    /**
                     * @description Whether to rerank the results. Defaults to `true`.
                     * @default true
                     */
                    rerank?: boolean;
                    /** @description The number of results to return after reranking. Defaults to `topK`. */
                    rerankLimit?: number;
                    /** @description A filter to apply to the results. */
                    filter?: {
                        [key: string]: unknown;
                    };
                    /** @description The minimum score to return. */
                    minScore?: number;
                    /**
                     * @description Whether to include relationships in the results. Defaults to `false`.
                     * @default false
                     */
                    includeRelationships?: boolean;
                    /**
                     * @description Whether to include metadata in the results. Defaults to `true`.
                     * @default true
                     */
                    includeMetadata?: boolean;
                };
            };
        };
        responses: {
            /** @description The retrieved namespace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: {
                            id: string;
                            score: number;
                            text?: string;
                            relationships?: {
                                [key: string]: unknown;
                            };
                            metadata?: {
                                file_directory: string;
                                filename: string;
                                filetype: string;
                                link_texts?: unknown[];
                                link_urls?: unknown[];
                                languages?: unknown[];
                                sequence_number?: number;
                            };
                        }[];
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            410: components["responses"]["410"];
            422: components["responses"]["422"];
            429: components["responses"]["429"];
            500: components["responses"]["500"];
        };
    };
}
